name: dotnet.yml
on: [on-pull-request]
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Message
      - run: echo "welcome"
  build:
    runs-on: ubuntu-latest
    needs: welcome
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - uses: actions/checkout@v3
